from __future__ import annotations

import os
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import (
    BaseDocTemplate,
    Frame,
    HRFlowable,
    Image as RLImage,
    PageTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)
from reportlab.platypus.flowables import Flowable

# ── Palette ───────────────────────────────────────────────────────────────────
GREEN_DARK  = colors.HexColor("#1B4332")
GREEN_MID   = colors.HexColor("#2D6A4F")
GREEN_LIGHT = colors.HexColor("#52B788")
GREEN_PALE  = colors.HexColor("#D8F3DC")
AMBER       = colors.HexColor("#E9C46A")
GREY_DARK   = colors.HexColor("#343A40")
GREY_MID    = colors.HexColor("#6C757D")
GREY_LIGHT  = colors.HexColor("#F8F9FA")
WHITE       = colors.white


# ── Custom flowables ──────────────────────────────────────────────────────────

class ColorRect(Flowable):
    """Solid-color rounded rectangle (decorative band)."""

    def __init__(self, width, height, fill_color, radius=4):
        super().__init__()
        self.width = width
        self.height = height
        self.fill_color = fill_color
        self.radius = radius

    def draw(self):
        self.canv.setFillColor(self.fill_color)
        self.canv.roundRect(0, 0, self.width, self.height, self.radius, fill=1, stroke=0)


class ConfBar(Flowable):
    """Horizontal progress-bar for confidence."""

    def __init__(self, pct: float, width: float = 10 * cm, height: float = 9):
        super().__init__()
        self.pct = min(max(pct, 0), 100)
        self.width = width
        self.height = height

    def draw(self):
        self.canv.setFillColor(colors.HexColor("#DEE2E6"))
        self.canv.roundRect(0, 0, self.width, self.height, self.height / 2, fill=1, stroke=0)
        fill_w = self.width * self.pct / 100
        if fill_w > 0:
            c = GREEN_LIGHT if self.pct >= 60 else AMBER
            self.canv.setFillColor(c)
            self.canv.roundRect(0, 0, fill_w, self.height, self.height / 2, fill=1, stroke=0)


# ── Header / footer on every page ─────────────────────────────────────────────

class _MyDocTemplate(BaseDocTemplate):

    def afterPage(self):  # noqa: N802
        cv = self.canv
        cv.saveState()
        w, h = A4

        # Top banner
        cv.setFillColor(GREEN_DARK)
        cv.rect(0, h - 1.8 * cm, w, 1.8 * cm, fill=1, stroke=0)
        cv.setFillColor(WHITE)
        cv.setFont("Helvetica-Bold", 13)
        cv.drawString(1.4 * cm, h - 1.2 * cm, "Open Insect Identifier")
        cv.setFont("Helvetica", 9)
        cv.setFillColor(GREEN_PALE)
        cv.drawRightString(w - 1.4 * cm, h - 1.2 * cm,
                           datetime.now().strftime("%d/%m/%Y  %H:%M"))

        # Bottom footer
        cv.setFillColor(GREY_LIGHT)
        cv.rect(0, 0, w, 1 * cm, fill=1, stroke=0)
        cv.setFillColor(GREY_MID)
        cv.setFont("Helvetica", 7.5)
        cv.drawString(1.4 * cm, 0.38 * cm, "Generated by Open Insect Identifier")
        cv.drawRightString(w - 1.4 * cm, 0.38 * cm, f"Page {cv._pageNumber}")  # type: ignore[attr-defined]

        cv.restoreState()


# ── Styles ────────────────────────────────────────────────────────────────────

def _build_styles():
    base = getSampleStyleSheet()
    return {
        "hero_title": ParagraphStyle(
            "hero_title", parent=base["Normal"],
            fontName="Helvetica-Bold", fontSize=20,
            textColor=WHITE, alignment=TA_CENTER, spaceAfter=2,
        ),
        "hero_sub": ParagraphStyle(
            "hero_sub", parent=base["Normal"],
            fontName="Helvetica", fontSize=9,
            textColor=GREEN_PALE, alignment=TA_CENTER,
        ),
        "section": ParagraphStyle(
            "section", parent=base["Normal"],
            fontName="Helvetica-Bold", fontSize=11,
            textColor=GREEN_DARK, spaceBefore=6, spaceAfter=4,
        ),
        "body": ParagraphStyle(
            "body", parent=base["Normal"],
            fontName="Helvetica", fontSize=9,
            textColor=GREY_DARK, leading=13, spaceAfter=3,
        ),
        "body_small": ParagraphStyle(
            "body_small", parent=base["Normal"],
            fontName="Helvetica", fontSize=8,
            textColor=GREY_MID, leading=11,
        ),
        "table_header": ParagraphStyle(
            "table_header", parent=base["Normal"],
            fontName="Helvetica-Bold", fontSize=9,
            textColor=WHITE, alignment=TA_CENTER,
        ),
        "table_cell": ParagraphStyle(
            "table_cell", parent=base["Normal"],
            fontName="Helvetica", fontSize=8,
            textColor=GREY_DARK, leading=11,
        ),
        "badge_ok": ParagraphStyle(
            "badge_ok", parent=base["Normal"],
            fontName="Helvetica-Bold", fontSize=9,
            textColor=WHITE, alignment=TA_CENTER,
        ),
        "badge_warn": ParagraphStyle(
            "badge_warn", parent=base["Normal"],
            fontName="Helvetica-Bold", fontSize=9,
            textColor=GREY_DARK, alignment=TA_CENTER,
        ),
        "link": ParagraphStyle(
            "link", parent=base["Normal"],
            fontName="Helvetica-Oblique", fontSize=8,
            textColor=GREEN_MID,
        ),
        "wiki_body": ParagraphStyle(
            "wiki_body", parent=base["Normal"],
            fontName="Helvetica", fontSize=8.5,
            textColor=GREY_DARK, leading=12,
        ),
    }


# ── Main ──────────────────────────────────────────────────────────────────────

def create_pdf_report(
    output_path: str,
    image_path: str | None,
    species_name: str | None,
    results_data: list[tuple[str, str, float, str | None]] | None,
    avg_conf: float | None,
    reliable: bool | None,
    gbif_url: str | None = None,
    wikipedia_summary: str | None = None,
) -> str:
    """Generate a single-page polished PDF report."""

    os.makedirs(os.path.dirname(output_path) if os.path.dirname(output_path) else ".", exist_ok=True)

    page_w, page_h = A4
    margin_lr  = 1.4 * cm
    margin_top = 2.0 * cm   # below header band
    margin_bot = 1.2 * cm   # above footer band
    content_w  = page_w - 2 * margin_lr

    doc = _MyDocTemplate(
        output_path,
        pagesize=A4,
        leftMargin=margin_lr,
        rightMargin=margin_lr,
        topMargin=margin_top,
        bottomMargin=margin_bot,
    )
    frame = Frame(
        margin_lr, margin_bot,
        content_w, page_h - margin_top - margin_bot,
        id="main",
    )
    doc.addPageTemplates([PageTemplate(id="main", frames=[frame])])

    styles = _build_styles()
    story  = []

    # ── Hero banner ───────────────────────────────────────────────────────────
    hero_content = [
        Paragraph(species_name or "Espèce inconnue", styles["hero_title"]),
        Spacer(1, 10),
        Paragraph("Rapport d'identification entomologique", styles["hero_sub"]),
    ]
    hero_table = Table([[hero_content]], colWidths=[content_w])
    hero_table.setStyle(TableStyle([
        ("BACKGROUND",   (0, 0), (-1, -1), GREEN_MID),
        ("ROUNDEDCORNERS", [6]),
        ("TOPPADDING",   (0, 0), (-1, -1), 14),
        ("BOTTOMPADDING",(0, 0), (-1, -1), 14),
        ("LEFTPADDING",  (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (-1, -1), 0),
        ("VALIGN",       (0, 0), (-1, -1), "MIDDLE"),
    ]))
    story.append(hero_table)

    story.append(Spacer(1, 0.3 * cm))

    # ── Row 1 : image | infos clés (2 colonnes) ──────────────────────────────
    col_w_img  = 6 * cm
    col_w_info = content_w - col_w_img

    # --- Column A : image
    col_img = []
    if image_path and os.path.exists(image_path):
        img = RLImage(image_path, width=5.5 * cm, height=5.5 * cm, kind="proportional")
        col_img.append(img)
        col_img.append(Spacer(1, 3))
        col_img.append(Paragraph("Image analysée", styles["body_small"]))
    else:
        col_img.append(Spacer(1, 1))

    # --- Column B : confidence badge + species info
    col_info = []
    col_info.append(Paragraph("Résultats", styles["section"]))

    if avg_conf is not None:
        badge_color = GREEN_LIGHT if reliable else AMBER
        bs = styles["badge_ok"] if reliable else styles["badge_warn"]
        label = f"{'Fiable' if reliable else 'Incertain'}  —  {avg_conf:.1f} %"
        bt = Table([[Paragraph(label, bs)]], colWidths=[6 * cm])
        bt.setStyle(TableStyle([
            ("BACKGROUND",   (0, 0), (-1, -1), badge_color),
            ("TOPPADDING",   (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING",(0, 0), (-1, -1), 5),
            ("LEFTPADDING",  (0, 0), (-1, -1), 8),
            ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ]))
        col_info.append(bt)
        col_info.append(Spacer(1, 5))
        col_info.append(ConfBar(avg_conf, width=6 * cm, height=9))
        col_info.append(Spacer(1, 6))

    if species_name:
        col_info.append(Paragraph(f"<b>Espèce :</b>  {species_name}", styles["body"]))
    if gbif_url:
        col_info.append(Paragraph(
            f"<b>GBIF :</b>  <a href='{gbif_url}' color='#2D6A4F'>{gbif_url}</a>",
            styles["link"],
        ))

    row1 = Table(
        [[col_img, col_info]],
        colWidths=[col_w_img, col_w_info],
        hAlign="LEFT",
    )
    row1.setStyle(TableStyle([
        ("VALIGN",       (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING",  (0, 0), (-1, -1), 0),
        ("RIGHTPADDING", (0, 0), (0, -1), 14),
        ("TOPPADDING",   (0, 0), (-1, -1), 0),
        ("BOTTOMPADDING",(0, 0), (-1, -1), 0),
    ]))
    story.append(row1)
    story.append(Spacer(1, 0.3 * cm))

    # ── Wikipedia : pleine largeur ────────────────────────────────────────────
    if wikipedia_summary:
        story.append(HRFlowable(width="100%", thickness=0.8, color=GREEN_PALE, spaceAfter=4))
        story.append(Paragraph("Résumé Wikipedia", styles["section"]))
        wt = Table([[Paragraph(wikipedia_summary, styles["wiki_body"])]], colWidths=[content_w])
        wt.setStyle(TableStyle([
            ("BACKGROUND",   (0, 0), (-1, -1), GREY_LIGHT),
            ("LEFTPADDING",  (0, 0), (-1, -1), 10),
            ("RIGHTPADDING", (0, 0), (-1, -1), 10),
            ("TOPPADDING",   (0, 0), (-1, -1), 8),
            ("BOTTOMPADDING",(0, 0), (-1, -1), 8),
            ("LINEBEFORE",   (0, 0), (0, -1), 3, GREEN_LIGHT),
        ]))
        story.append(wt)
        story.append(Spacer(1, 0.3 * cm))

    # ── Species table ─────────────────────────────────────────────────────────
    if results_data:
        story.append(HRFlowable(width="100%", thickness=0.8, color=GREEN_PALE, spaceAfter=4))
        story.append(Paragraph("Espèces ressemblantes", styles["section"]))

        header = [
            Paragraph("Niveau",           styles["table_header"]),
            Paragraph("Nom scientifique", styles["table_header"]),
            Paragraph("Confiance",        styles["table_header"]),
            Paragraph("Barre",            styles["table_header"]),
        ]
        rows = [header]
        for level, name, conf, _ in results_data:
            rows.append([
                Paragraph(level, styles["table_cell"]),
                Paragraph(name,  styles["table_cell"]),
                Paragraph(f"{conf:.0f} %", styles["table_cell"]),
                ConfBar(conf, width=3.8 * cm, height=8),
            ])

        col_widths = [2.8 * cm, 7.2 * cm, 2.2 * cm, 4.3 * cm]
        tbl = Table(rows, colWidths=col_widths, hAlign="LEFT", repeatRows=1)
        tbl.setStyle(TableStyle([
            # Header row — fond vert foncé, texte BLANC
            ("BACKGROUND",    (0, 0), (-1, 0), GREEN_DARK),
            ("TEXTCOLOR",     (0, 0), (-1, 0), WHITE),
            ("FONTNAME",      (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE",      (0, 0), (-1, 0), 9),
            ("ALIGN",         (0, 0), (-1, 0), "CENTER"),
            # Data rows alternées
            ("ROWBACKGROUNDS",(0, 1), (-1, -1), [WHITE, GREEN_PALE]),
            ("FONTNAME",      (0, 1), (-1, -1), "Helvetica"),
            ("FONTSIZE",      (0, 1), (-1, -1), 8),
            # Grille
            ("GRID",          (0, 0), (-1, -1), 0.4, colors.HexColor("#CED4DA")),
            ("LINEBELOW",     (0, 0), (-1, 0), 1.2, GREEN_MID),
            # Padding
            ("TOPPADDING",    (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ("LEFTPADDING",   (0, 0), (-1, -1), 7),
            ("RIGHTPADDING",  (0, 0), (-1, -1), 7),
            ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
        ]))
        story.append(tbl)

    doc.build(story)
    return output_path